# Builder
FROM python:3.12-slim AS builder

WORKDIR /dockerapp

RUN pip install uv

COPY pyproject.toml uv.lock ./

RUN uv sync --no-dev

COPY app/ ./app/

# Stage 2
FROM python:3.12-slim

WORKDIR /dockerapp

COPY --from=builder /dockerapp/.venv /dockerapp/.venv

COPY --from=builder /dockerapp/app /dockerapp/app

ENV PATH="/dockerapp/.venv/bin:$PATH"

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]