# Builder
FROM python:3.12-slim AS builder

WORKDIR /dockerapp

RUN pip install uv

COPY pyproject.toml uv.lock ./

RUN uv sync --no-dev

COPY app/ ./app/

COPY alembic/ ./alembic/
COPY alembic.ini ./alembic.ini

# Stage 2
FROM python:3.12-slim

WORKDIR /dockerapp

COPY --from=builder /dockerapp/.venv /dockerapp/.venv

COPY --from=builder /dockerapp/app /dockerapp/app

COPY --from=builder /dockerapp/alembic /dockerapp/alembic
COPY --from=builder /dockerapp/alembic.ini /dockerapp/alembic.ini

ENV PATH="/dockerapp/.venv/bin:$PATH"

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]