apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: llm-gateway-cluster
  region: us-east-2

nodeGroups:
  - name: standard-workers
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3