"""add email to api_key, cache_hit and latency_ms to request_log

Revision ID: a2a00bc9f3c7
Revises: df79089c6545
Create Date: 2026-08-21 16:55:47.181948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2a00bc9f3c7'
down_revision: Union[str, Sequence[str], None] = 'df79089c6545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_key', sa.Column('email', sa.String(), nullable=True))
    op.add_column('request_log', sa.Column('cache_hit', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('request_log', sa.Column('latency_ms', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_log', 'latency_ms')
    op.drop_column('request_log', 'cache_hit')
    op.drop_column('api_key', 'email')
    # ### end Alembic commands ###
